default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  port: <%= ENV.fetch("PGPORT") { 5432 } %>
  username: <%= ENV.fetch("PGUSER") { ENV["USER"] } %>
  password: <%= ENV["PGPASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library_management_development

test:
  <<: *default
  database: library_management_test

production:
  <<: *default
  database: library_management_production
